### ISSUE TITLE
Ming Xiang - Quora Clone terminal issue

### ISSUE THREAD

**Issue by mingxiangchan** [hollowaykeanho/sinatra-web-server#14]
Terminal printed out below when running rake db:create or rake db: drop
rake db:create
/questions/:id
/users/:id
/answers/:id
Create database quora-clone_development if it doesn't exist...

Only place the /questions/:id was created was in controllers in below form:

    7  # show specific questions
    8: get '/questions/:id' do
    9  end
   10  
   ..
   14  
   15  # change existing questions info
   16: puts '/questions/:id' do 
   17  end
   18  
   19  # delete questions records from database
   20: delete '/questions/:id' do 
   21  end

**Comment by joshteng** [comment]
@mingxiangchan thx for the comment. probably a good idea to add a screenshot of your terminal output as well!

**Comment by mingxiangchan** [comment]
Noted. Below is the screenshot of my terminal output. 

I ran $ shotgun config.ru, $ rake db:drop, $ rake db:create
![securitywarning](https://cloud.githubusercontent.com/assets/14155919/10355122/a0b06d20-6d9a-11e5-886a-bc1cff1cb2ba.png)

**Comment by hollowaykeanho** [comment]
Will this bug affects your main production?

**Comment by mingxiangchan** [comment]
Not affecting production, just an additional 3 lines of output on terminal when running operations

**Comment by hollowaykeanho** [comment]
Cool. I will mark this bug as low priority since it's related to terminal printout and not affecting the production line.

Thanks for reporting.

**Comment by mingxiangchan** [comment]
Manged to find the bug. The terminal output stopped displaying the additional lines after I commented out the unused routes in my controllers. Routes with defined blocks will not affect the terminal output.

E.g. unused routes as follows:
puts '/users/:id' do 
end

delete '/users/:id' do 
end

**Comment by hollowaykeanho** [comment]
I don't think this is a bug. 

The put you're using is ***puts*** instead of ***put*** as documented n Sinatra README: http://www.sinatrarb.com/intro.html. Please re-test and update.

**Comment by mingxiangchan** [comment]
Confirmed its because of the puts command that is printing to console. Issue closed.
