### ISSUE TITLE
Helper issue

### ISSUE THREAD

**Issue by mingxiangchan** [hollowaykeanho/sinatra-web-server#15]
/config/environments/init.rb file does not load helpers

**Comment by hollowaykeanho** [comment]
Accepted as bug issue. Fixing bug.

**Comment by hollowaykeanho** [comment]
Bug fixed under https://github.com/hollowaykeanho/sinatra-web-server/commit/757e62a490cd5f8b372f1786405549674a05bc36. 

Released as hotfix.
