### ISSUE TITLE
Security warning for sessions

### ISSUE THREAD

**Issue by mingxiangchan** [hollowaykeanho/sinatra-web-server#16]
Received security warning on terminal output when running server

Screenshot:
![securitywarning](https://cloud.githubusercontent.com/assets/14155919/10355018/3f8b25c2-6d99-11e5-8a04-c9a9f5fc3318.png)

Checked online and found a reference on the issue:
http://stackoverflow.com/questions/18044627/sinatra-1-4-3-use-racksessioncookie-warning

Was able to get rid of issue by adding a line:
set :session_secret, 'this is a secret shhhhh'

**Comment by hollowaykeanho** [comment]
Recognized as a configuration bug due to double initialization.

**Comment by hollowaykeanho** [comment]
Solved as hotfix - commit id: c168453f62da3d09a63481910ba61ada6be219b5.

Please git pull or cherry-pick the commit for hotfix. Thank you.
