### ISSUE TITLE
Unable to transfer assets to Heroku

### ISSUE THREAD

**Issue by bryanlyt** [hollowaykeanho/sinatra-web-server#17]
Issues with deploying app to Heroku, unable to load assets. 

(screenshots as attached)

1. localhost screenshot: 
http://s15.postimg.org/xcvojc1cb/Screen_Shot_2015_10_27_at_11_20_46_AM.png

2. heroku screenshot: 
http://s15.postimg.org/xblqpwzij/Screen_Shot_2015_10_27_at_11_21_02_AM.png

3. "failed to load resources (css, js, images)
http://s15.postimg.org/fo3xrppl7/Screen_Shot_2015_10_27_at_11_21_36_AM.png

**Comment by hollowaykeanho** [comment]
This app is not packed with public folder. Ticket accepted. Upgrading.

**Comment by hollowaykeanho** [comment]
Commited under b7437732b651c230581529d8794ba55b19696ac7. Please test and provide feedback.

Thank you.

**Comment by bryanlyt** [comment]
Tested and working. Thanks!
